// 태그리스 설치 체크리스트 — 단일 공통 양식(엑셀 "태크리스 체크리스트" 시트에서 추출, 병합정보 포함)
// 표출형(B700/B710/B800)에서만 사용. 일반 모델 점검표(models.generated.ts)와 동일한 CkRowDef 구조.
import type { CkModel, CkRowDef } from "./types";

/** 태그리스 체크박스를 노출할 모델(표출형) */
export const TAGLESS_MODELS: CkModel[] = ["B700", "B710", "B800"];

/** 태그리스 점검행 체크키용 모델 키(일반 모델과 충돌 방지) */
export const TAGLESS_CHECK_KEY = "__TAGLESS__";

export const CK_TAGLESS_DATA: { title: string; rows: CkRowDef[] } = {
  title: "태그리스 설치 체크 리스트",
  rows: [
    {
      caseNo: 1,
      caseLabel: "FW",
      target: "태그리스 FW 설치 버전 확인",
      item: "",
      method: "단말기 설정 진입 후 확인",
      point: "태그리스 FW :                        비콘 FW :",
      kind: "taglessFwVer",
      bigo: "1. USB 업데이트\r\n2. 태그리스 사용설정\r\n3. 전원 Off-On",
      bigoKind: "static",
      m: {"caseNo": [3, 1], "caseLabel": [3, 1], "target": [1, 2], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [2, 1]},
    },
    {
      caseNo: 1,
      caseLabel: "FW",
      target: "태그리스 사용여부 설정",
      item: "",
      method: "단말기 설정 진입 후 확인",
      point: "태그리스 사용설정 확인\r\n설정 ▶ 차량정보설정 ▶ 태그리스 사용설정",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"target": [1, 2], "method": [1, 1], "point": [1, 1], "ox": [1, 1]},
    },
    {
      caseNo: 1,
      caseLabel: "FW",
      target: "단말기 FW 버전확인",
      item: "",
      method: "단말기 설정 진입 후 확인",
      point: "AFC :                               G/W :",
      kind: "deviceFwVer",
      bigo: "",
      bigoKind: "static",
      m: {"target": [1, 2], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 2,
      caseLabel: "H/W",
      target: "통합단말기",
      item: "내 / 외관 확인",
      method: "커넥터 고정상태",
      point: "통신상태 확인 및 시간확인, 케이블 체결상태 확인                  러버패드 부착상태 확인, 블랙 커버 조립상태 확인 ,",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"caseNo": [11, 1], "caseLabel": [11, 1], "target": [1, 1], "item": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 2,
      caseLabel: "H/W",
      target: "허브",
      item: "LED 확인",
      method: "부팅/통신/체결상태 확인",
      point: "외부 LED 점등상태, 커넥터 체결상태 확인, 케이블 네임택 확인\r\n(B700/800 CI(통합단말기 측), MAIN_HUB(허브 측)\r\n스크류 체결상태 확인",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"target": [1, 1], "item": [8, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 2,
      caseLabel: "H/W",
      target: "비콘1",
      item: "",
      method: "부팅/통신/체결상태 확인",
      point: "외부 LED 점등상태, 커넥터 체결상태 확인, 케이블 번호 확인(0),스크류 체결상태 확인",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"target": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 2,
      caseLabel: "H/W",
      target: "비콘2",
      item: "",
      method: "부팅/통신/체결상태 확인",
      point: "외부 LED 점등상태, 커넥터 체결상태 확인, 케이블 번호 확인(1),\r\n스크류 체결상태 확인",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"target": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 2,
      caseLabel: "H/W",
      target: "비콘3",
      item: "",
      method: "부팅/통신/체결상태 확인",
      point: "외부 LED 점등상태, 커넥터 체결상태 확인, 케이블 번호 확인(2),\r\n스크류 체결상태 확인",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"target": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 2,
      caseLabel: "H/W",
      target: "비콘4",
      item: "",
      method: "부팅/통신/체결상태 확인",
      point: "외부 LED 점등상태, 커넥터 체결상태 확인, 케이블 번호 확인(3),\r\n스크류 체결상태 확인",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"target": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 2,
      caseLabel: "H/W",
      target: "비콘5",
      item: "",
      method: "부팅/통신/체결상태 확인",
      point: "외부 LED 점등상태, 커넥터 체결상태 확인, 케이블 번호 확인(4),\r\n스크류 체결상태 확인",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"target": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 2,
      caseLabel: "H/W",
      target: "비콘6",
      item: "",
      method: "부팅/통신/체결상태 확인",
      point: "외부 LED 점등상태, 커넥터 체결상태 확인, 케이블 번호 확인(5),\r\n스크류 체결상태 확인",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"target": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 2,
      caseLabel: "H/W",
      target: "비콘7",
      item: "",
      method: "부팅/통신/체결상태 확인",
      point: "외부 LED 점등상태, 커넥터 체결상태 확인, 케이블 번호 확인(6),\r\n스크류 체결상태 확인",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"target": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 2,
      caseLabel: "H/W",
      target: "브라켓 및 케이블 고정상태 확인",
      item: "",
      method: "브라켓 고정,케이블 \r\n고정 타이 마감",
      point: "브라켓 고정상태(1번 비콘),\r\n케이블의 케이블타이 작업 유무 확인",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"target": [1, 2], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 2,
      caseLabel: "H/W",
      target: "외부안테나 마감상태",
      item: "",
      method: "고정상태 확인",
      point: "커넥터 조임 및 외부 안테나 0, 1, 2 실리콘 마감상태",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"target": [1, 2], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 3,
      caseLabel: "운행     대기중",
      target: "표출단말기",
      item: "시간확인",
      method: "운전자단말기 화면에서 왼쪽 \r\n상단에 현재일시 현시 확인",
      point: "현재일시 제대로 현시",
      kind: "time",
      bigo: "시간/분 표기",
      bigoKind: "static",
      m: {"caseNo": [3, 1], "caseLabel": [3, 1], "target": [1, 1], "item": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 3,
      caseLabel: "운행     대기중",
      target: "허브",
      item: "통신 및 정보 확인",
      method: "외부 LED 작동여부 확인",
      point: "",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"target": [1, 1], "item": [2, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 3,
      caseLabel: "운행     대기중",
      target: "비콘",
      item: "",
      method: "비콘별 통신상태 확인",
      point: "0:                 1:                2:               3:\r\n4:                 5:                6:",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"target": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 3,
      caseLabel: "운행\r\n대기중",
      target: "표출단말기    상태바 정보 확인",
      item: "CITS표출부 GPS Icon",
      method: "",
      point: "CITS표출바 상태바에 GPS Icon 활성화.                                    Ant Bar가 3개이상",
      icon: "/checklist/icon-gps.png",
      kind: "check",
      onlyModel: "B700",
      bigo: "B700 대상",
      bigoKind: "static",
      m: {"caseNo": [9, 1], "caseLabel": [9, 1], "target": [7, 1], "item": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 3,
      caseLabel: "운행\r\n대기중",
      target: "",
      item: "CITS표출부             단말운영 Icon",
      method: "",
      point: "CITS표출부 상태바에 T Icon 이                                           흰색 실선으로 표출",
      icon: "/checklist/icon-t.png",
      kind: "check",
      onlyModel: "B700",
      bigo: "B700 대상",
      bigoKind: "static",
      m: {"item": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 3,
      caseLabel: "운행\r\n대기중",
      target: "",
      item: "AFC표출부 LTE Icon",
      method: "",
      point: "AFC표출부 상태바에 LTE Icon 활성화.                                 Ant Bar가 4개 이상",
      icon: "/checklist/icon-lte.png",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"item": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 3,
      caseLabel: "운행\r\n대기중",
      target: "",
      item: "AFC표출부              단말운영센터 Icon",
      method: "",
      point: "AFC표출부 상태바에 T Icon 이                                            흰색 실선으로 표출",
      icon: "/checklist/icon-t.png",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"item": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 3,
      caseLabel: "운행\r\n대기중",
      target: "",
      item: "AFC표출부              수집센터 Icon",
      method: "",
      point: "AFC표출부 상태바에 D Icon 이                                            흰색 실선으로 표출",
      icon: "/checklist/icon-d.png",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"item": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 3,
      caseLabel: "운행\r\n대기중",
      target: "",
      item: "AFC표출부           BMS센터 Icon",
      method: "",
      point: "AFC표출부 상태바에 B Icon 이                                             흰색 실선으로 표출",
      icon: "/checklist/icon-b.png",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"item": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 3,
      caseLabel: "운행\r\n대기중",
      target: "",
      item: "승하차                    통신 연결 확인",
      method: "",
      point: "표출부에 승하차단말기 테두리 녹색으로 표기",
      icon: "/checklist/icon-check.png",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"item": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 3,
      caseLabel: "운행\r\n대기중",
      target: "표출단말기    ",
      item: "시간확인",
      method: "표출단말기 화면에서 왼쪽          상단에 현재일시 현시 확인",
      point: "현재일시 제대로 현시",
      kind: "time",
      bigo: "시간/분",
      bigoKind: "static",
      m: {"target": [2, 1], "item": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 3,
      caseLabel: "운행\r\n대기중",
      target: "",
      item: "태그리스 설정",
      method: "BLE 아이콘 확인",
      point: "B700 화면상단 BLE표시 / B800 화면 우측 상단표시 확인",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"item": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 4,
      caseLabel: "운행중",
      target: "비콘",
      item: "신호 송신여부",
      method: "비콘 번호별 신호 확인",
      point: "앱 내 설치 차량번호 입력(ex. 747208)",
      kind: "appVehicleNo",
      bigo: "",
      bigoKind: "static",
      m: {"caseNo": [2, 1], "caseLabel": [2, 1], "target": [2, 1], "item": [2, 1], "method": [2, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 4,
      caseLabel: "운행중",
      target: "",
      item: "",
      method: "",
      point: "테스트 앱 실행 후 각 비콘, 외부안테나에 근접시켜 해당 비콘\r\n번호의 신호 bar가 강해지는지 확인",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 5,
      caseLabel: "운행종료",
      target: "운전자단말기,\r\n승.하차단말기",
      item: "운행종료",
      method: "운전자단말기에서 [운행] ▶ [확인]",
      point: "1.운전자단말기에서 '운행을 종료합니다' 음성 출력\r\n2.종료 처리 정상여부 확인",
      kind: "check",
      bigo: "",
      bigoKind: "static",
      m: {"caseNo": [2, 1], "caseLabel": [2, 1], "target": [1, 1], "item": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 5,
      caseLabel: "운행종료",
      target: "운전자단말기,\r\n승.하차단말기",
      item: "거래내역전송",
      method: "[운행종료]후 미전송 거래내역 파일갯수 확인",
      point: "미전송거래내역 파일:0",
      kind: "check",
      bigo: "\"미전송 발생시\r\n 센터장보고\"",
      bigoKind: "static",
      m: {"target": [1, 1], "item": [1, 1], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
    {
      caseNo: 6,
      caseLabel: "특이사항",
      target: "추가 자재사용 내역 및 특이사항",
      item: "",
      method: "운전자 봉 / 승하차 봉 etc. \r\n브라켓 등",
      point: "내용기재",
      kind: "etc",
      bigo: "수량 : ",
      bigoKind: "etcQty",
      m: {"caseNo": [1, 1], "caseLabel": [1, 1], "target": [1, 2], "method": [1, 1], "point": [1, 1], "ox": [1, 1], "bigo": [1, 1]},
    },
  ],
};
